package com.sample.gateway.rest.fixture;

import com.sample.gateway.core.domain.Application;
import com.sample.gateway.core.event.RegisteredApplicationEvent;
import com.sample.gateway.core.event.RetrievedApplicationEvent;

import java.util.Date;

/**
 * Created with IntelliJ IDEA.
 * User: paullawler
 * Date: 2/17/14
 * Time: 1:48 PM
 * To change this template use File | Settings | File Templates.
 */
public class ApplicationEventFixtures {

    public static RegisteredApplicationEvent applicationRegistered(Long applicationId) {
        Application data = registerApplication();
        data.setApplicationId(applicationId);
        data.setApprovedOn(new Date());
        data.setRegisteredOn(new Date());
        data.setApproved(true);
        return new RegisteredApplicationEvent(data);
    }

    public static RetrievedApplicationEvent applicationRetrieved(Long applicationId) {
        RegisteredApplicationEvent event = applicationRegistered(applicationId);
        return new RetrievedApplicationEvent(event.getData()); // could decorate? interesting...
    }

    public static Application registerApplication() {
        Application data = Application.newInstance(1L, "Test ApplicationEntity Fixture", "http://localhost:9000/testapplication");

        data.setDescription("This is data generated by a fixture class for unit testing");
        data.setRedirectUri("http://localhost:9000/testapplication");
        data.setAdminUri("http://localhost:9000/testadmin");
        data.setAdmin(false);
        data.setBulkExtract(false);

        return data;
    }

}
