package com.sample.gateway.rest.fixture;

import com.sample.gateway.core.domain.Application;
import com.sample.gateway.core.event.ApplicationData;
import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.map.ObjectMapper;

import java.io.IOException;

/**
 * Created with IntelliJ IDEA.
 * User: paullawler
 * Date: 2/17/14
 * Time: 1:55 PM
 * To change this template use File | Settings | File Templates.
 */
public class DataFixtures {

    public static String applicationJson() throws IOException {
        ApplicationData data = new ApplicationData();
        data.setApplicationName("Test Application Fixture");
        data.setDescription("This is data generated by a fixture class for unit testing");
        data.setAdminUri("http://localhost:9000/testapplication");

        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writeValueAsString(data);
        return json;
    }
}
